name: follow-me-cpu

dependencies:
  - python==3.7
  - pip
  - matplotlib
  - opencv
  - pip:
    - opencv-python==4.1.1.26
    - lxml
    - tqdm
    - tensorflow==2.3.0
    - absl-py
    - easydict
    - pillow
    - PyYAML
    - pandas